# Generated by Django 4.1.7 on 2023-03-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('repo', models.URLField()),
                ('demo', models.URLField(blank=True)),
                ('screenshot', models.ImageField(upload_to='')),
                ('project_created', models.DateTimeField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testamonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=150)),
                ('reference_title', models.CharField(max_length=200)),
                ('reference_testamonial', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
