# Generated by Django 4.1.7 on 2023-03-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Testamonials',
            new_name='Testamonial',
        ),
    ]
