# Generated by Django 4.1.7 on 2023-03-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testamonial',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
    ]
