# Generated by Django 4.1.7 on 2023-03-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_testamonial_reference_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testamonial',
            new_name='Testimonial',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='reference_testamonial',
            new_name='reference_testimonial',
        ),
    ]
