# Generated by Django 4.1.7 on 2023-03-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_testamonial_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_created',)},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('reference_name',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='reference_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
