# Generated by Django 4.1.7 on 2023-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(upload_to='projects/<django.db.models.fields.CharField>'),
        ),
    ]
