# Generated by Django 4.1.7 on 2023-03-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_created',
            field=models.DateField(db_index=True),
        ),
    ]
